# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '7.x.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: dotnet build MyApp.sln --configuration Release
            displayName: 'Build Solution'

  - stage: Test
    displayName: 'Test Stage'
    dependsOn: Build
    jobs:
      - job: Test
        steps:
          - script: dotnet test MyApp.Tests/MyApp.Tests.csproj --configuration Release --no-build
            displayName: 'Run Unit Tests'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying to production..."
            displayName: 'Deploy Script Placeholder'
